version: '3'

services:

  yetibot:
    image: yetibot/yetibot
    depends_on:
      - postgres
    environment:
      - YB_ADAPTERS_FREENODE_TYPE=irc
      - YB_ADAPTERS_FREENODE_HOST=irc.freenode.net
      - YB_ADAPTERS_FREENODE_PORT=6667
      - YB_ADAPTERS_FREENODE_USERNAME=yetibot_demo
      - YB_DB_URL=postgresql://yetibot:yetibot@postgres:5432/yetibot
      - YB_URL=http://localhost:3456
    ports:
      - "3456:3003"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=yetibot
      - POSTGRES_PASSWORD=yetibot
    ports:
      - 5432

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=events
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"

  riemann:
    image: riemannio/riemann
    ports:
      - "127.0.0.1:5555:5555"
      - "127.0.0.1:5555:5555/udp"
      - "127.0.0.1:5556:5556"
    volumes:
      - ./riemann.config:/etc/riemann.config
